# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PBTimeline' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PBTimeline

  target 'PBTimelineTests' do
    # Pods for testing
  end

end

target 'PBTimelineExamples' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PBTimelineExamples

end
